In [ ]:
                                                                    DAY 3 Sync

In [ ]:
# 1. Challenge 1: The "Manual to Vectorized" Shift
#                 -Goal: Prove they can stop using for loops.
#                 -Task: Provide the intern with this dictionary and ask them to:
#                 -Convert it to a DataFrame.
#                 -Create a new column Total_Cost by multiplying Price and Quantity.
#                 -Constraint: They are forbidden from using for, while, or iterrows().

In [23]:
import pandas as pd 
import numpy as np 
import csv

In [4]:
df = pd.DataFrame(data = {
    'Item': ['Widget A', 'Widget B', 'Widget C'],
    'Price': [25.50, 40.00, 15.75],
    'Quantity': [10, 5, 20]
})

In [5]:
df

       Item  Price  Quantity
0  Widget A  25.50        10
1  Widget B  40.00         5
2  Widget C  15.75        20

In [13]:
df['Total Cost'] = df['Price'] * df['Quantity']

In [14]:
df

       Item  Price  Quantity  Total Cost
0  Widget A  25.50        10       255.0
1  Widget B  40.00         5       200.0
2  Widget C  15.75        20       315.0

In [ ]:
# 2. Challenge 2: The Titanic Data Audit
#                 -Goal: Practical data cleaning and filtering.
#                 -Task: Ask the intern to download the Titanic CSV and write a script that outputs a "Report" containing:
#                 -The count of missing values in every column.
#                 -A new DataFrame called young_passengers containing only people aged 18 or younger.
#                 -The average Fare paid by people in young_passengers.
#                 -Replace all missing values in the Embarked column with the string "Unknown".

In [86]:
data = pd.read_csv(r"D:\DataEngineering\Pandas\Titanic-Dataset.csv")

In [89]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [90]:
# count of missing values in every column 
# data.isna
data.isna().count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            891
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          891
Embarked       891
dtype: int64

In [91]:
# creating new dataframe 
young_passengers = data[data['Age'] <= 18]

In [93]:
young_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q

In [94]:
# finding the average fare of passengers 

averagefare_of_young_passengers = young_passengers['Fare'].mean()
print("Average Fare = ", averagefare_of_young_passengers )

Average Fare =  32.50072086330935

In [95]:
# replacing the null values 

data["Embarked"] = data["Embarked"].fillna("unknown")

In [97]:
# again checking missing values in data after replacing with unknown
print(data["Embarked"].isnull().sum())

0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
852,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C

In [ ]:
# 3. Challenge 3: The "Difficult" One – String & Data Cleaning
# -Goal: Handling real-world "dirty" data in Pandas.
# -The Setup: Give them this messy DataFrame:

# # df = pd.DataFrame({
# #     'Date': ['2023-01-01', '2023-01-02', 'Missing', '2023-01-04'],
# #     'Revenue': ['$1,200', '$2,500', 'ERROR', '$1,800'],
# #     'Active_Users': [150, np.nan, 200, 175]
# # })    

                # -The Mission: Write a script to "sanitize" this data:
                # -The Date Trap: Convert the Date column to datetime objects. (They will need to handle the "Missing" string—hint: errors='coerce').
                # -The Currency Trap: Convert Revenue into a clean float. They must remove the $ and the , and handle the "ERROR" string.
                # -The Null Trap: Fill the missing Active_Users with the mean value of that column.
                # -The Final Output: Print df.info() and the final cleaned DataFrame.

In [99]:
df2 = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-02', 'Missing', '2023-01-04'],
    'Revenue': ['$1,200', '$2,500', 'ERROR', '$1,800'],
    'Active_Users': [150, np.nan, 200, 175]
})

In [100]:
df2

         Date Revenue  Active_Users
0  2023-01-01  $1,200         150.0
1  2023-01-02  $2,500           NaN
2     Missing   ERROR         200.0
3  2023-01-04  $1,800         175.0

In [101]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          4 non-null      str
 1   Revenue       4 non-null      str
 2   Active_Users  3 non-null      float64
dtypes: float64(1), str(2)
memory usage: 228.0 bytes

In [107]:
df2['Date'] = pd.to_datetime(df2['Date'], errors='coerce')

In [108]:
df2.info() # datatype change of Date column

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3 non-null      datetime64[us]
 1   Revenue       4 non-null      str
 2   Active_Users  3 non-null      float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 228.0 bytes

In [130]:
df2['Revenue'] = df2['Revenue'].str.replace(r"[$,]", "", regex = True)
df2

        Date Revenue  Active_Users
0 2023-01-01    1200         150.0
1 2023-01-02    2500           NaN
2        NaT   ERROR         200.0
3 2023-01-04    1800         175.0

In [134]:
df2['Revenue'] = pd.to_numeric(df2['Revenue'], errors='coerce')

In [136]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3 non-null      datetime64[us]
 1   Revenue       3 non-null      float64
 2   Active_Users  3 non-null      float64
dtypes: datetime64[us](1), float64(2)
memory usage: 228.0 bytes

In [137]:
df2

        Date  Revenue  Active_Users
0 2023-01-01   1200.0         150.0
1 2023-01-02   2500.0           NaN
2        NaT      NaN         200.0
3 2023-01-04   1800.0         175.0

In [141]:
 df2["Active_Users"] = df2["Active_Users"].fillna(df2["Active_Users"].mean())

In [142]:
df2

        Date  Revenue  Active_Users
0 2023-01-01   1200.0         150.0
1 2023-01-02   2500.0         175.0
2        NaT      NaN         200.0
3 2023-01-04   1800.0         175.0

In [144]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          3 non-null      datetime64[us]
 1   Revenue       3 non-null      float64
 2   Active_Users  4 non-null      float64
dtypes: datetime64[us](1), float64(2)
memory usage: 228.0 bytes

In [ ]:
1. Challenge 1: The "Sales Insights" Aggregator
-Goal: Master the groupby() and agg() functions.
-The Task: Provide this dataset of sales transactions. The intern must write a script that calculates two things:
-The total revenue per Category.
-The average quantity sold per Region.
Code:
# import pandas as pd

# sales_data = {
#     'Region': ['North', 'South', 'North', 'East', 'South', 'East'],
#     'Category': ['Electronics', 'Furniture', 'Electronics', 'Electronics', 'Furniture', 'Furniture'],
#     'Revenue': [1200, 800, 1500, 2100, 450, 700],
#     'Quantity': [3, 2, 4, 5, 1, 2]
# }
# df = pd.DataFrame(sales_data)
-Requirement: Output a summary DataFrame showing Total Revenue by Category.

In [145]:
sales_data = {
    'Region': ['North', 'South', 'North', 'East', 'South', 'East'],
    'Category': ['Electronics', 'Furniture', 'Electronics', 'Electronics', 'Furniture', 'Furniture'],
    'Revenue': [1200, 800, 1500, 2100, 450, 700],
    'Quantity': [3, 2, 4, 5, 1, 2]
}

In [146]:
sd = pd.DataFrame(sales_data)

In [147]:
sd

  Region     Category  Revenue  Quantity
0  North  Electronics     1200         3
1  South    Furniture      800         2
2  North  Electronics     1500         4
3   East  Electronics     2100         5
4  South    Furniture      450         1
5   East    Furniture      700         2

In [189]:
sd.groupby("Category")["Revenue"].sum()

Category
Electronics    4800
Furniture      1950
Name: Revenue, dtype: int64

In [190]:
sd.groupby("Region")["Quantity"].mean()

Region
East     3.5
North    3.5
South    1.5
Name: Quantity, dtype: float64

In [184]:
sd.groupby("Category").agg({
    "Revenue" : ["sum", "mean"],
})

            Revenue
                sum    mean
Category
Electronics    4800  1600.0
Furniture      1950   650.0

In [185]:
sd["Total_By_Category"] = sd.groupby("Category")["Revenue"].transform("sum")

In [186]:
s

  Region     Category  Revenue  Quantity  Total_By_Category
0  North  Electronics     1200         3               4800
1  South    Furniture      800         2               1950
2  North  Electronics     1500         4               4800
3   East  Electronics     2100         5               4800
4  South    Furniture      450         1               1950
5   East    Furniture      700         2               1950

In [188]:
sd.groupby("Category").filter(lambda x:x ["Revenue"].sum() > 2000)

  Region     Category  Revenue  Quantity  Total_By_Category
0  North  Electronics     1200         3               4800
2  North  Electronics     1500         4               4800
3   East  Electronics     2100         5               4800